-- Flash Furniture order-level induction analysis (past 3 months)
-- Parent supplier: Flash Furniture

SELECT
  supplier_id,
  su_name,
  parent_su_name,
  city_name,
  state_name,
  postal_code,
  address_1,
  StationName,
  sto,
  ProductCategory,
  srm_contact,
  ops,
  purchase_order_number,
  tracking_number,
  order_complete_date,
  order_dow,
  msbd_su,
  msbd_cu,
  induction_date_lidd,
  induction_dow_adj,
  carrier_first_induction_date_time,
  fulfillment_ship_date_time,
  event_datetime,
  sp_lt,
  order_lt,
  cushion,
  OrderCapacityPadDays,
  cutoff,
  o2s_actual,
  o2sumsbd,
  o2cumsbd,
  inducted_on_time_or_early,
  inducted_early,
  inducted_late,
  inducted_over_weekend,
  not_inducted_but_late_already,
  not_inducted_not_late_yet,
  one_day_late,
  two_day_late,
  three_five_day_inducted_late,
  three_days_plus_late,
  label_by_msbd_7,
  label_by_msbd_2,
  o2label_0_adj,
  o2label_1_adj,
  label2I_0_adj,
  label2I_1_adj,
  label2I_2_adj,
  o2I_0_adj,
  o2I_1_adj,
  o2I_2_adj,
  assigned_induction_hub_name,
  actual_induction_hub_name,
  assignedhub_notequal_actualhub_flag,
  destination_state,
  delivery_date,
  delivery_rel,
FROM `wf-gcp-us-ae-global-tnd-prod.speed_and_reliability.HVE_perf_Monitoring`
WHERE msbd_su >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH)
  AND parent_su_name = 'Flash Furniture'
ORDER BY msbd_su DESC, supplier_id, ops
